
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Apr 01 20:29:41 CEST 2014
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int AND = 30;
  public static final int LT = 26;
  public static final int ELSE = 18;
  public static final int CLASS = 13;
  public static final int SEMICOLON = 5;
  public static final int NOTEQ = 29;
  public static final int PLUS = 22;
  public static final int OR = 32;
  public static final int RBRACE = 9;
  public static final int RPAREN = 12;
  public static final int INT = 2;
  public static final int WHILE = 19;
  public static final int NOT = 24;
  public static final int RETURN = 20;
  public static final int IDENTIFIER = 3;
  public static final int IF = 17;
  public static final int GT = 27;
  public static final int LPAREN = 11;
  public static final int LBRACE = 8;
  public static final int THIS = 16;
  public static final int COMMA = 7;
  public static final int EOF = 0;
  public static final int MULT = 6;
  public static final int DIV = 25;
  public static final int MINUS = 23;
  public static final int error = 1;
  public static final int DOT = 4;
  public static final int EQ = 10;
  public static final int INTEGER_LITERAL = 33;
  public static final int NEW = 21;
  public static final int XOR = 31;
  public static final int EQEQ = 28;
  public static final int EXTENDS = 14;
  public static final int VOID = 15;
  public static final int NULL_LITERAL = 34;
}

